application: mpsanalysis
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /upload/.*
  script: upload.py

- url: /export/.*
  script: export.py

- url: /results.*
  script: results.py

- url: /.*
  script: main.py
